import { useState } from 'react';
import { Carousel } from '../components/Carousel.jsx';
import { GalleryModal } from '../components/Modal.jsx';

export function Home({ content }) { return <main><section className="page hero"><div><Carousel label="Featured Rangari work" items={content.home?.carousel || []} /><div className="hero-copy"><p className="eyebrow">Rangari Art Studio</p><h1>{content.home?.title}</h1><p>{content.home?.description}</p><a className="button" href="/gallery">View gallery</a></div></div></section></main>; }

export function About({ content }) { const profile = content.about?.carousel?.[0]; return <main><section className="page about"><div><p className="eyebrow">About Rangari</p><h1>{content.about?.title}</h1><p className="about-copy">{content.about?.content}</p></div><div><Carousel label="About Rangari" items={content.about?.carousel || []} />{profile && <article className="profile"><h2>{profile.title}</h2><p>{profile.description}</p></article>}</div></section></main>; }

export function Gallery({ content }) { const [selected, setSelected] = useState(null); return <main><section className="page"><p className="eyebrow">Selected work</p><h1>Gallery</h1><p className="intro">Explore Rangari projects. Select a project to view its images.</p><div className="gallery-grid">{content.gallery.map((card) => <button className="gallery-card" type="button" key={card.id || card.legacy_id || card.title} onClick={() => setSelected(card)}><img src={card.primaryImage} alt={`${card.title} project preview`} /><span><strong>{card.title}</strong><small>{card.description}</small></span></button>)}</div></section><GalleryModal card={selected} onClose={() => setSelected(null)} /></main>; }

export function Contact({ content }) { const [status, setStatus] = useState(''); const submit = (event) => { event.preventDefault(); const values = new FormData(event.currentTarget); if (!event.currentTarget.reportValidity()) return; const number = String(content.footer?.whatsapp_number || content.footer?.phone || '').replace(/\D/g, ''); const message = `Hello, I'm ${values.get('name').trim()}.\nMy email is: ${values.get('email').trim()}.\n\nMy message is:\n${values.get('message').trim()}`; window.open(`https://wa.me/${number}?text=${encodeURIComponent(message)}`, '_blank', 'noopener'); setStatus('WhatsApp is opening in a new tab.'); }; return <main><section className="page contact"><div><p className="eyebrow">Visit or write</p><h1>Contact us</h1><iframe className="map" title="Map to Rangari Art Studio" loading="lazy" referrerPolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15085.662418993907!2d72.84216648817943!3d19.045456273525!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c992e5b70361%3A0xd45dce1d63987e68!2sRANGARI%20art%20studio!5e0!3m2!1sen!2sin!4v1750706215075!5m2!1sen!2sin" /></div><form className="contact-form" onSubmit={submit}><label>Your name<input name="name" autoComplete="name" required /></label><label>Your email<input name="email" type="email" autoComplete="email" required /></label><label>Your message<textarea name="message" rows="6" required /></label><button className="button">Send via WhatsApp</button><p aria-live="polite">{status}</p></form></section></main>; }
